### ISSUE TITLE
Needless state triggering in onSwipe?

### ISSUE THREAD

**Issue by Muthaias** [Greenheart/swipeforfuture.com#39] opened 2019-12-30 00:57 UTC
https://github.com/Greenheart/swipeforfuture.com/blob/fa0ce2f71d13bd47954cd23c7799d28bb775c796/src/components/Game.js#L106

I don't really understand why you want to trigger another state change after setting the updated world. This can easily be done using a single setState. Is there reason for this?

I would prefer the following implementation:
https://github.com/Muthaias/swipeforfuture.com/blob/29e8169213f2b50d71c7037623a212d13da29324/src/components/Game.js#L108

I'll make a merge request when my previous merge request has been considered.

**Comment by Greenheart** [comment] 2019-12-30 01:05
Good catch!

This is intended, since we need the updated state before selecting the next card. We could potentially use `updatedWorld` to calculate the `nextCard` like we did initially - but I didn't get it to work earlier, so I chose this solution instead.

**Comment by Greenheart** [comment] 2019-12-30 01:08
It seems like your approach should work too. I'll try to change it back.

The problems I encountered earlier might have been caused by other things.

**Comment by Greenheart** [comment] 2019-12-30 01:52
This is fixed by https://github.com/Greenheart/swipeforfuture.com/commit/92ba141cbc22db51e0c11bf9733ab8c2440a661e

**Closed by Greenheart** 2019-12-30 01:52 UTC
